- hosts: localhost
  gather_facts: no

  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ item }}"
      template: "{{ template_vm }}"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ folder_name }}"
      state: poweredon
      wait_for_ip_address: yes
    register: "r"
    with_items: "{{ serv }}" 

  - debug : 
      msg: "This is the Host-IPs: {{ item.instance.ipv4 }} {{ item.instance.hw_name }}"
    with_items: "{{ r.results}}"
    loop_control:
      label: "{{ item.instance.hw_name }}"

  - shell: "echo {{ item.instance.ipv4 }} {{ item.instance.hw_name }} >> /tmp/servertips"
    with_items: "{{ r.results}}"
    loop_control:
      label: "{{ item.instance.hw_name }}"

